# vim: set ft=ansible :
---
- name: install apache
  apt: >
    pkg={{item}}
  with_items:
    - apache2
    - libapache2-mod-php5

- name: remove stock index.html
  file: >
    dest=/var/www/index.html
    state=absent
